apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: spring-apps
  source:
    repoURL: 'https://github.com/aragonne/DemoManifests.git'
    path: demoargo
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: spring-apps-dev
  syncPolicy:
    automated: {}
