apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aragonne/rollouts-demo.git'
    path: examples/blue-green
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bluegreen
  syncPolicy:
    automated: {}
