apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmargo-config
  namespace: argocd
spec:
  project: spring-apps
  source:
    repoURL: 'https://github.com/aragonne/DemoConfig.git'
    path: .
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: spring-apps-dev
  syncPolicy:
    automated: {}
